apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip-01"
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app.kubernetes.io/component: primary