apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: service-a
spec:
  host: service-a
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      outlierDetection:
        consecutive5xxErrors: 1     # 连续 1 次 5xx 错误触发熔断
        interval: 3s               # 每 3 秒检查一次
        baseEjectionTime: 30s       # 熔断后驱逐 30 秒
        maxEjectionPercent: 100     # 最多可以熔断 100% 的实例
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      outlierDetection:
        consecutive5xxErrors: 1
        interval: 3s
        baseEjectionTime: 30s
        maxEjectionPercent: 100