apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    proxy.istio.io/config: |
      proxyMetadata: {}
      proxyHeaders:
        requestHeaders:
          x-api-version: {}  # 明确启用这个头
        forwarded: true