##################################################################################################
# service-a
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    service: service-a
spec:
  ports:
  - port: 10001
    name: http
  selector:
    app: service-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-a
  labels:
    account: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v1
  labels:
    app: service-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: v1
  template:
    metadata:
      labels:
        app: service-a
        version: v1
    spec:
      serviceAccountName: demo-service-a
      containers:
      - name: service-a
        image: kkk2099/kkk:service-a-1.0
        imagePullPolicy: Always
        env:
        - name: JVM_MEM
          value: "1G"
        - name: APP_VERSION
          value: "v1"
        - name: APP_KUBERNETES_ENABLED
          value: "true"
        - name: SERVICE_B_URI
          value: "http://service-b:10002"
        ports:
        - containerPort: 10001
        resources:
          requests:
            memory: "1.5Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v2
  labels:
    app: service-a
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
      version: v2
  template:
    metadata:
      labels:
        app: service-a
        version: v2
    spec:
      serviceAccountName: demo-service-a
      containers:
      - name: service-a
        image: kkk2099/kkk:service-a-1.0
        imagePullPolicy: Always
        env:
        - name: JVM_MEM
          value: "1G"
        - name: APP_VERSION
          value: "v2"
        - name: APP_KUBERNETES_ENABLED
          value: "true"
        - name: SERVICE_B_URI
          value: "http://service-b:10002"
        ports:
        - containerPort: 10001
        resources:
          requests:
            memory: "1.5Gi"
---
##################################################################################################
# service-b
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
    service: service-b
spec:
  ports:
  - port: 10002
    name: http
  selector:
    app: service-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-b
  labels:
    account: service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-v1
  labels:
    app: service-b
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: v1
  template:
    metadata:
      labels:
        app: service-b
        version: v1
    spec:
      serviceAccountName: demo-service-b
      containers:
      - name: service-b
        image: kkk2099/kkk:service-b-1.0
        imagePullPolicy: Always
        env:
        - name: APP_KUBERNETES_ENABLED
          value: "true"
        - name: APP_VERSION
          value: "v1"
        ports:
        - containerPort: 10002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-v2
  labels:
    app: service-b
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: v2
  template:
    metadata:
      labels:
        app: service-b
        version: v2
    spec:
      serviceAccountName: demo-service-b
      containers:
      - name: service-b
        image: kkk2099/kkk:service-b-1.0
        imagePullPolicy: Always
        env:
        - name: APP_KUBERNETES_ENABLED
          value: "true"
        - name: APP_VERSION
          value: "v2"
        ports:
        - containerPort: 10002
---
##################################################################################################
# api-gateway
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    service: gateway
spec:
  ports:
  - port: 10000
    name: http
  selector:
    app: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-gateway
  labels:
    account: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: demo-gateway
      containers:
      - name: gateway
        image: kkk2099/kkk:gateway-1.0
        imagePullPolicy: Always
        env:
        - name: JVM_MEM
          value: "1G"
        - name: APP_KUBERNETES_ENABLED
          value: "true"
        - name: SERVICE_A_URI
          value: "http://service-a:10001"
        ports:
        - containerPort: 10000
        resources:
          requests:
            memory: "1.5Gi"
---
##################################################################################################
# frontend-react
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: frontend-react
  labels:
    app: frontend-react
    service: frontend-react
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: frontend-react
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-frontend-react
  labels:
    account: frontend-react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-v1
  labels:
    app: frontend-react
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
      version: v1
  template:
    metadata:
      labels:
        app: frontend-react
        version: v1
    spec:
      serviceAccountName: demo-frontend-react
      containers:
      - name: frontend-react
        image: kkk2099/kkk:react-1.0
        imagePullPolicy: Always
        env:
        - name: GATEWAY_URL
          value: "http://gateway.default.svc.cluster.local:10000"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react-v2
  labels:
    app: frontend-react
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
      version: v2
  template:
    metadata:
      labels:
        app: frontend-react
        version: v2
    spec:
      serviceAccountName: demo-frontend-react
      containers:
      - name: frontend-react
        image: kkk2099/kkk:react-2.0
        imagePullPolicy: Always
        env:
        - name: GATEWAY_URL
          value: "http://gateway.default.svc.cluster.local:10000"
        ports:
        - containerPort: 80
---