apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: service-a
spec:
  host: service-a
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 1      # 最大并发连接数为1
      outlierDetection:
        consecutive5xxErrors: 1   # 连续出现1次5xx错误就触发熔断
        interval: 1s             # 检测间隔1秒
        baseEjectionTime: 10s    # 熔断持续10秒
        maxEjectionPercent: 100  # 可以熔断所有实例
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 1      # 最大并发连接数为1
      outlierDetection:
        consecutive5xxErrors: 1   # 连续出现1次5xx错误就触发熔断
        interval: 1s             # 检测间隔1秒
        baseEjectionTime: 10s    # 熔断持续10秒
        maxEjectionPercent: 100  # 可以熔断所有实例
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: service-b
spec:
  host: service-b
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend-react
spec:
  host: frontend-react
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gateway
spec:
  host: gateway
---
