apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: propagate-headers
spec:
  hosts:
  - service-b
  http:
  - route:
    - destination:
        host: service-b
    headers:
      request:
        add:
          x-api-version: "111111"  # 使用 metadata 的值