apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: service-a
spec:
  hosts:
  - service-a
  http:
  - match:
    - headers:
        x-version-id:
          exact: v1
    route:
    - destination:
        host: service-a
        subset: v1
  - route:
    - destination:
        host: service-a
        subset: v2
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: service-b
spec:
  hosts:
  - service-b
  http:
  - match:
    - headers:
        x-version-id:
          exact: v1
    route:
    - destination:
        host: service-b
        subset: v1
  - route:
    - destination:
        host: service-b
        subset: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-react
spec:
  hosts:
  - frontend-react
  http:
  - match:
    - headers:
        x-version-id:
          exact: v1
    route:
    - destination:
        host: frontend-react
        subset: v1
  - route:
    - destination:
        host: frontend-react
        subset: v2
---
