apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - 43.128.112.69
  extraArgs:
    advertise-address: "43.128.112.69"
controlPlaneEndpoint: "43.128.112.69:6443"
etcd:
  local:
    extraArgs:
      listen-peer-urls: "https://127.0.0.1:2380"
      listen-client-urls: "https://127.0.0.1:2379"
      advertise-client-urls: "https://127.0.0.1:2379"
      initial-advertise-peer-urls: "https://127.0.0.1:2380"
      initial-cluster: "vm-8-14-debian=https://127.0.0.1:2380"