apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: custom-tags
  namespace: istio-system
spec:
  metrics:
    - overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT
          tagOverrides:
            destination_x:
              value: upstream_peer.labels['app'].value
        - match:
            metric: REQUEST_COUNT
            mode: SERVER
          tagOverrides:
            source_x:
              value: downstream_peer.labels['app'].value
      providers:
        - name: prometheus



---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: service-a-custom-tags
spec:
  metrics:
    - overrides:
      - match:
          metric: ALL_METRICS
          mode: SERVER
        tagOverrides:
          method:
            value: request.method
          istio_operationId:
            value: | 
              request.url_path.matches("/api/v1/[[:alnum:]]*/keys/[[:alnum:]]*/import") ? "/api/v1/{cusID}/keys/{keyName}/import" :
              request.url_path.matches("/api/v1/[[:alnum:]]*/keys/[[:alnum:]]*/revolve") ? "/api/v1/{cusID}/keys/{keyName}/revolve" :
              request.url_path.matches("/api/v1/[[:alnum:]]*/encode") ? "/api/v1/{cusID}/encode" :
              request.url_path.matches("/api/v1/[[:alnum:]]*/decode") ? "/api/v1/{cusID}/decode" :
              request.url_path.matches("/ready") ? "probes" :
              request.url_path.matches("/live") ? "probes" :
              "unknown"
      providers:
        - name: prometheus
  selector:
    matchLabels:
      app: service-a